# -*- coding: utf-8 -*-
"""Watermarking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6gqTV1joDMp8Nh--SfgqCC3eCqTngsj
"""

"""
Tugas Watermarking

Nama  : Riko Satriya Giovanni
NIM   : 18224108
Kelas : K-02

Cara pakai:
  1. Letakkan foto wajah dengan nama 'face.jpg' di folder yang sama.
  2. Jalankan:  python watermarking_dct.py
  3. Semua output (gambar & laporan) otomatis tersimpan di folder  ./output/

"""

import os
import io
import cv2
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from PIL import Image
from scipy.fftpack import dct, idct

# 0. KONFIGURASI
INPUT_IMAGE   = "face.jpg" #foto yang ingin di watermark
OUTPUT_DIR    = "output"
BLOCK_SIZE    = 8
ALPHA         = 25
QF_LIST       = [90, 70, 50, 30, 10]

# Koefisien blok 8×8 yang dipakai untuk menyisipkan (zigzag mid-freq)
EMBED_COORDS  = [(4, 1), (3, 2), (2, 3), (1, 4)]

os.makedirs(OUTPUT_DIR, exist_ok=True)


# 1. FUNGSI UTILITAS DCT 2-D BLOK
def dct2(block):
    """Forward 2-D DCT pada blok 8×8."""
    return dct(dct(block.T, norm="ortho").T, norm="ortho")

def idct2(block):
    """Inverse 2-D DCT pada blok 8×8."""
    return idct(idct(block.T, norm="ortho").T, norm="ortho")


# 2. GENERATE WATERMARK BINER -> Huruf "R" (Sesuai dengan inisial nama saya: Riko)
def generate_watermark(rows=None, cols=None) -> np.ndarray:
    """
    Watermark biner 32x32 berisi huruf 'R' yang presisi dan proporsional.
    Bit: 1 = putih, 0 = hitam.
    """
    WM_SIZE = 32
    wm = np.zeros((WM_SIZE, WM_SIZE), dtype=np.uint8)

    # ── 1. Batang vertikal kiri (|) ─────────────────────────────
    wm[6:26, 7:11] = 1

    # ── 2. Garis horizontal atas dan tengah kepala ──────────────
    wm[6:10, 11:19] = 1
    wm[14:18, 11:18] = 1

    # ── 3. Lengkungan kanan kepala (Bentuk 'D' dari huruf 'R') ──
    wm[7:17, 18:21] = 1
    wm[8:16, 21:23] = 1
    wm[9:15, 23:24] = 1
    wm[10:14, 24:25] = 1

    wm[10, 18] = 0
    wm[13, 18] = 0

    # ── 4. Kaki diagonal kanan bawah (\) ────────────────────────
    for r in range(16, 26):
        c_start = int(13 + (r - 16) * 1.1)
        wm[r, c_start:c_start+4] = 1

    # ── 5. Border tipis (bingkai watermark) ─────────────────────
    wm[0, :]  = 1;  wm[-1, :] = 1
    wm[:, 0]  = 1;  wm[:, -1] = 1

    return wm

def watermark_to_bits(wm: np.ndarray) -> np.ndarray:
    return wm.flatten()

def bits_to_watermark(bits: np.ndarray, shape=(32, 32)) -> np.ndarray:
    n = shape[0] * shape[1]
    return bits[:n].reshape(shape)


# 3. EMBEDDING (PENYISIPAN WATERMARK)
def embed_watermark(image_rgb: np.ndarray,
                    wm_bits: np.ndarray,
                    alpha: float = ALPHA) -> np.ndarray:
    """
    Sisipkan watermark ke komponen Y (Luminance) via DCT blok 8×8.
    Mengembalikan gambar RGB ter-watermark.
    """
    # Konversi ke YCbCr
    img_ycbcr = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2YCrCb).astype(np.float64)
    Y = img_ycbcr[:, :, 0]

    h, w = Y.shape
    bit_idx = 0
    total_bits = len(wm_bits)

    for row in range(0, h - BLOCK_SIZE + 1, BLOCK_SIZE):
        for col in range(0, w - BLOCK_SIZE + 1, BLOCK_SIZE):
            if bit_idx >= total_bits:
                break
            block = Y[row:row+BLOCK_SIZE, col:col+BLOCK_SIZE]
            D = dct2(block)

            for (u, v) in EMBED_COORDS:
                if bit_idx >= total_bits:
                    break
                bit = wm_bits[bit_idx]
                # Quantization Index Modulation (QIM) sederhana:
                # Koefisien dipaksa ke kelipatan alpha yang sesuai paritas bit
                coef = D[u, v]
                q    = round(coef / alpha)
                if q % 2 != bit:
                    q += 1 if (bit == 1) else -1
                D[u, v] = q * alpha
                bit_idx += 1

            Y[row:row+BLOCK_SIZE, col:col+BLOCK_SIZE] = idct2(D)

    Y = np.clip(Y, 0, 255)
    img_ycbcr[:, :, 0] = Y
    watermarked_rgb = cv2.cvtColor(img_ycbcr.astype(np.uint8), cv2.COLOR_YCrCb2RGB)
    print(f"  [Embed] {bit_idx} bit disisipkan dari total {total_bits} bit watermark.")
    return watermarked_rgb


# 4. JPEG COMPRESSION SIMULATION
def jpeg_compress(image_rgb: np.ndarray, quality: int) -> np.ndarray:
    """Simulasi kompresi JPEG pada quality factor tertentu, kembalikan array RGB."""
    pil_img = Image.fromarray(image_rgb)
    buf = io.BytesIO()
    pil_img.save(buf, format="JPEG", quality=quality)
    buf.seek(0)
    compressed = np.array(Image.open(buf))
    return compressed


# 5. EXTRACTION (EKSTRAKSI WATERMARK)
def extract_watermark(image_rgb: np.ndarray,
                      total_bits: int,
                      alpha: float = ALPHA) -> np.ndarray:
    """Ekstrak bit watermark dari gambar (setelah kompresi)."""
    img_ycbcr = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2YCrCb).astype(np.float64)
    Y = img_ycbcr[:, :, 0]

    h, w = Y.shape
    extracted_bits = []
    bit_idx = 0

    for row in range(0, h - BLOCK_SIZE + 1, BLOCK_SIZE):
        for col in range(0, w - BLOCK_SIZE + 1, BLOCK_SIZE):
            if bit_idx >= total_bits:
                break
            block = Y[row:row+BLOCK_SIZE, col:col+BLOCK_SIZE]
            D = dct2(block)

            for (u, v) in EMBED_COORDS:
                if bit_idx >= total_bits:
                    break
                coef = D[u, v]
                q    = round(coef / alpha)
                extracted_bits.append(int(q % 2))
                bit_idx += 1

    return np.array(extracted_bits[:total_bits], dtype=np.uint8)


# 6. METRIK EVALUASI
def normalized_correlation(orig_bits: np.ndarray, ext_bits: np.ndarray) -> float:
    """NC: 1.0 = identik, 0.0 = tidak ada korelasi."""
    o = orig_bits.astype(np.float64) * 2 - 1   # {0,1} → {-1,+1}
    e = ext_bits.astype(np.float64)  * 2 - 1
    denom = np.sqrt(np.sum(o**2) * np.sum(e**2))
    return float(np.dot(o, e) / denom) if denom != 0 else 0.0

def bit_error_rate(orig_bits: np.ndarray, ext_bits: np.ndarray) -> float:
    """BER: 0.0 = sempurna, 0.5 = acak total."""
    return float(np.mean(orig_bits != ext_bits))

def psnr(img1: np.ndarray, img2: np.ndarray) -> float:
    """Peak Signal-to-Noise Ratio antara dua gambar."""
    mse = np.mean((img1.astype(np.float64) - img2.astype(np.float64))**2)
    return 100.0 if mse == 0 else 10 * np.log10(255**2 / mse)


# 7. VISUALISASI HASIL
def save_comparison_figure(original, watermarked, results, wm_orig_img, wm_extracted_list):
    """Simpan figure besar: perbandingan gambar + watermark terekstrak per QF."""
    n_qf = len(results)
    fig = plt.figure(figsize=(5 * (n_qf + 2), 10), facecolor="#0f0f1a")

    gs = gridspec.GridSpec(
        2, n_qf + 2,
        figure=fig,
        hspace=0.4, wspace=0.3,
        left=0.03, right=0.97, top=0.88, bottom=0.08
    )

    title_kw  = dict(color="white", fontsize=11, fontweight="bold", pad=6)
    label_kw  = dict(color="#aaaacc", fontsize=9)

    # ── Baris 1: Foto Asli & Foto Watermarked ──
    ax_orig = fig.add_subplot(gs[0, 0])
    ax_orig.imshow(original);  ax_orig.axis("off")
    ax_orig.set_title("Foto Asli", **title_kw)

    ax_wm = fig.add_subplot(gs[0, 1])
    ax_wm.imshow(watermarked); ax_wm.axis("off")
    ax_wm.set_title(f"Foto + Watermark\nPSNR={psnr(original, watermarked):.1f} dB", **title_kw)

    # ── Baris 1: Foto terkompresi per QF ──
    for i, res in enumerate(results):
        ax = fig.add_subplot(gs[0, i + 2])
        ax.imshow(res["compressed"])
        ax.axis("off")
        ax.set_title(f"QF = {res['qf']}", **title_kw)
        ax.text(0.5, -0.04,
                f"NC={res['nc']:.3f}  BER={res['ber']:.3f}\nPSNR={res['psnr_wm']:.1f}dB",
                ha="center", va="top", transform=ax.transAxes, **label_kw)

    # ── Baris 2: Watermark asli & terekstrak per QF ──
    ax_wm_orig = fig.add_subplot(gs[1, 0:2])
    ax_wm_orig.imshow(wm_orig_img, cmap="gray", vmin=0, vmax=1)
    ax_wm_orig.axis("off")
    ax_wm_orig.set_title("Watermark Asli (32×32)", **title_kw)

    for i, (res, wm_ext) in enumerate(zip(results, wm_extracted_list)):
        ax = fig.add_subplot(gs[1, i + 2])
        ax.imshow(wm_ext, cmap="gray", vmin=0, vmax=1)
        ax.axis("off")
        status = "✓ VALID" if res["nc"] >= 0.5 else "✗ RUSAK"
        color  = "#00ff99" if res["nc"] >= 0.5 else "#ff4444"
        ax.set_title(f"QF={res['qf']}  {status}", color=color,
                     fontsize=10, fontweight="bold", pad=6)

    fig.suptitle(
        "Evaluasi Kinerja DCT Watermarking terhadap Kompresi JPEG",
        color="white", fontsize=15, fontweight="bold", y=0.96
    )
    path = os.path.join(OUTPUT_DIR, "evaluation_result.png")
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"  [Save] {path}")
    return path


def save_metrics_chart(results):
    """Simpan grafik NC & BER vs QF."""
    qf_vals  = [r["qf"]  for r in results]
    nc_vals  = [r["nc"]  for r in results]
    ber_vals = [r["ber"] for r in results]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5), facecolor="#0f0f1a")
    for ax in (ax1, ax2):
        ax.set_facecolor("#1a1a2e")
        ax.tick_params(colors="white"); ax.xaxis.label.set_color("white")
        ax.yaxis.label.set_color("white"); ax.title.set_color("white")
        for spine in ax.spines.values(): spine.set_edgecolor("#444466")

    # NC
    ax1.plot(qf_vals, nc_vals, "o-", color="#00ccff", lw=2.5, ms=8, label="NC")
    ax1.axhline(0.5, color="#ff6666", ls="--", lw=1.5, label="Threshold NC=0.5")
    ax1.fill_between(qf_vals, nc_vals, 0.5,
                     where=[v >= 0.5 for v in nc_vals], alpha=0.2, color="#00ccff")
    ax1.set_xlabel("Quality Factor (QF)"); ax1.set_ylabel("NC")
    ax1.set_title("Normalized Correlation vs QF")
    ax1.set_ylim(-0.1, 1.1); ax1.legend(facecolor="#1a1a2e", labelcolor="white")
    ax1.set_xticks(qf_vals)

    # BER
    ax2.plot(qf_vals, ber_vals, "s-", color="#ff9944", lw=2.5, ms=8, label="BER")
    ax2.axhline(0.3, color="#ff6666", ls="--", lw=1.5, label="Threshold BER=0.3")
    ax2.fill_between(qf_vals, ber_vals, 0.3,
                     where=[v >= 0.3 for v in ber_vals], alpha=0.2, color="#ff9944")
    ax2.set_xlabel("Quality Factor (QF)"); ax2.set_ylabel("BER")
    ax2.set_title("Bit Error Rate vs QF")
    ax2.set_ylim(-0.05, 0.6); ax2.legend(facecolor="#1a1a2e", labelcolor="white")
    ax2.set_xticks(qf_vals)

    fig.suptitle("Grafik Metrik Ketahanan Watermark",
                 color="white", fontsize=13, fontweight="bold")
    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, "metrics_chart.png")
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"  [Save] {path}")
    return path


def print_report(results):
    """Cetak tabel evaluasi ke terminal dan simpan ke .txt."""
    header = f"\n{'='*62}\n  TABEL EVALUASI KINERJA WATERMARK (DCT-QIM, α={ALPHA})\n{'='*62}"
    row_fmt = "  QF={:<4} | NC={:.4f} | BER={:.4f} | PSNR_wm={:.2f} dB | {}"
    lines = [header]
    lines.append(f"  {'QF':<6}{'NC':>8}{'BER':>8}{'PSNR(dB)':>12}  Status")
    lines.append("  " + "-"*56)

    valid_qf = []; broken_qf = []
    for r in results:
        status = "VALID  ✓" if r["nc"] >= 0.5 else "RUSAK  ✗"
        lines.append(row_fmt.format(r["qf"], r["nc"], r["ber"], r["psnr_wm"], status))
        (valid_qf if r["nc"] >= 0.5 else broken_qf).append(r["qf"])

    lines.append("  " + "-"*56)
    if valid_qf and broken_qf:
        lines.append(f"\n  ✅ Watermark TAHAN  hingga QF = {min(valid_qf)}")
        lines.append(f"  ❌ Watermark RUSAK  mulai  QF = {max(broken_qf)}")
    elif not broken_qf:
        lines.append("\n  ✅ Watermark TAHAN di semua QF yang diuji.")
    else:
        lines.append("\n  ❌ Watermark RUSAK di semua QF yang diuji.")
    lines.append("="*62)

    report = "\n".join(lines)
    print(report)

    path = os.path.join(OUTPUT_DIR, "evaluation_report.txt")
    with open(path, "w") as f:
        f.write(report)
    print(f"  [Save] {path}")


# 8. MAIN PIPELINE
def main():
    # ── Load gambar ──────────────────────────────────────────
    if not os.path.exists(INPUT_IMAGE):
        print(f"[INFO] '{INPUT_IMAGE}' tidak ditemukan – membuat foto dummy 256×256.")
        # Buat dummy wajah sederhana agar script bisa ditest tanpa foto
        dummy = np.full((256, 256, 3), 180, dtype=np.uint8)
        cv2.ellipse(dummy, (128,110), (70,85), 0, 0, 360, (210,175,130), -1)  # wajah
        cv2.circle(dummy, (105,105), 10, (80,50,30), -1)   # mata kiri
        cv2.circle(dummy, (151,105), 10, (80,50,30), -1)   # mata kanan
        cv2.ellipse(dummy, (128,155), (30,15), 0, 0, 180, (160,80,80), 2)    # mulut
        cv2.imwrite(INPUT_IMAGE, cv2.cvtColor(dummy, cv2.COLOR_RGB2BGR))

    img_bgr  = cv2.imread(INPUT_IMAGE)
    img_rgb  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # Resize agar minimal cukup menampung watermark 32×32 bit
    # (butuh ≥ ceil(1024/4)=256 blok → 128×128 piksel minimum)
    min_dim = 256
    h, w = img_rgb.shape[:2]
    if h < min_dim or w < min_dim:
        scale  = max(min_dim/h, min_dim/w)
        img_rgb = cv2.resize(img_rgb, (int(w*scale), int(h*scale)))
    print(f"\n[Load] Gambar: {img_rgb.shape[1]}×{img_rgb.shape[0]} piksel")

    # ── Watermark ────────────────────────────────────────────
    wm_img  = generate_watermark(*img_rgb.shape[:2])
    wm_bits = watermark_to_bits(wm_img)
    print(f"[WM]   Watermark: {wm_img.shape}, {len(wm_bits)} bit")

    # ── Embedding ────────────────────────────────────────────
    print("\n[Step 1] Embedding watermark ke foto...")
    wm_image = embed_watermark(img_rgb, wm_bits, alpha=ALPHA)

    # Simpan foto asli & foto watermarked
    cv2.imwrite(os.path.join(OUTPUT_DIR, "original.jpg"),
                cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR), [cv2.IMWRITE_JPEG_QUALITY, 95])
    cv2.imwrite(os.path.join(OUTPUT_DIR, "watermarked.png"),
                cv2.cvtColor(wm_image, cv2.COLOR_RGB2BGR))

    psnr_orig_wm = psnr(img_rgb, wm_image)
    print(f"  PSNR (Asli vs Watermarked): {psnr_orig_wm:.2f} dB")

    # ── Loop QF ──────────────────────────────────────────────
    print("\n[Step 2] Kompresi JPEG & Ekstraksi Watermark...")
    results = []; wm_extracted_list = []

    for qf in QF_LIST:
        print(f"\n  ── QF = {qf} ──")
        compressed = jpeg_compress(wm_image, quality=qf)
        ext_bits   = extract_watermark(compressed, len(wm_bits), alpha=ALPHA)

        nc  = normalized_correlation(wm_bits, ext_bits)
        ber = bit_error_rate(wm_bits, ext_bits)
        p   = psnr(wm_image, compressed)
        print(f"     NC={nc:.4f}  BER={ber:.4f}  PSNR_compressed={p:.2f}dB")

        ext_img = bits_to_watermark(ext_bits, shape=wm_img.shape)
        wm_extracted_list.append(ext_img)

        # Simpan gambar terkompresi
        out_path = os.path.join(OUTPUT_DIR, f"compressed_qf{qf}.jpg")
        cv2.imwrite(out_path, cv2.cvtColor(compressed, cv2.COLOR_RGB2BGR),
                    [cv2.IMWRITE_JPEG_QUALITY, 95])

        results.append({"qf": qf, "nc": nc, "ber": ber,
                         "psnr_wm": p, "compressed": compressed})

    # ── Visualisasi ──────────────────────────────────────────
    print("\n[Step 3] Menyimpan visualisasi...")
    save_comparison_figure(img_rgb, wm_image, results, wm_img, wm_extracted_list)
    save_metrics_chart(results)
    print_report(results)

    print(f"\n✅ Selesai! Semua output tersimpan di folder: ./{OUTPUT_DIR}/")


if __name__ == "__main__":
    main()